startuml


class Jugador {
+seleccionar()
}

class Tablero {
+minas
+numeros
}

class Minas {
+posicion
+explotar()
}

class Numeros {
+alrededor()
}

Tablero --* Minas
Tablero --* Numeros
Jugador --> Minas


@enduml
